import {HttpCodesTypes} from './types';

export const HttpCodes: HttpCodesTypes = {
  SUCCESS: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  UNAUTHORIZED_LOGOUT: 418,
  NOT_FOUND: 404,
  AWAITING_LIBERATION: 419,
  APPLICATION_EXCEPTION: 420,
  INTERNAL_SERVER_ERROR: 500,
};
